# Generated by Django 3.2.6 on 2021-08-14 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0003_auto_20210810_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='type',
            new_name='type_old',
        ),
    ]
