# Generated by Django 3.2.6 on 2021-08-14 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0004_rename_type_issue_type_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='type',
            field=models.ManyToManyField(default=1, related_name='issues', to='issue_tracker.Type', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='type_old',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='issues_set', to='issue_tracker.type', verbose_name='Тип'),
        ),
    ]
