# Generated by Django 3.2.6 on 2021-08-14 08:33

from django.db import migrations
from django.db.migrations import RunPython


def transfer_types(apps, schema_editor):
    Issue = apps.get_model('issue_tracker.Issue')
    Type = apps.get_model('issue_tracker.Type')
    for issue in Issue.objects.all():
        issue_types = Type.objects.filter(issues__id=issue.id)
        issue.type.set(issue_types)


def rollback_types(apps, schema_editor):
    Issue = apps.get_model('issue_tracker.Issue')
    for issue in Issue.objects.all():
        issue.type_old.set(issue.type.all())


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0005_auto_20210814_1416'),
    ]

    operations = [
        RunPython(transfer_types, rollback_types)
    ]
