# Generated by Django 3.2.6 on 2021-08-14 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0006_auto_20210814_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='type_old',
        ),
    ]
