# Generated by Django 3.2.6 on 2021-08-17 10:46

from django.db import migrations, models
import issue_tracker.helpers.validators


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0007_remove_issue_type_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(validators=[issue_tracker.helpers.validators.body_at_least_7], verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='summary',
            field=models.CharField(max_length=150, validators=[issue_tracker.helpers.validators.title_with_create_input], verbose_name='Краткое описание'),
        ),
    ]
