# Generated by Django 3.2.6 on 2021-09-14 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0014_auto_20210914_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectusers',
            old_name='users',
            new_name='user',
        ),
    ]
