# Generated by Django 3.2.6 on 2021-09-17 14:59

from django.db import migrations


def create_profile(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    User = apps.get_model('auth', 'User')

    for user in User.objects.all():
        Profile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_profile, migrations.RunPython.noop)
    ]
