# Generated by Django 3.2.6 on 2021-09-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210917_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='imageNotAvailable_grid.png', upload_to='user_avatars'),
        ),
    ]
