# Generated by Django 3.2.6 on 2021-09-17 18:24

from django.db import migrations


def add_default_photo(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')

    for profile in Profile.objects.all():
        if not profile.avatar:
            profile.avatar = None
            profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.RunPython(
            add_default_photo, migrations.RunPython.noop
        )
    ]
