# Generated by Django 3.2.6 on 2021-09-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210918_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='user_avatars/imageNotAvailable_grid.png', upload_to='user_avatars'),
        ),
    ]
